version: '3.8'
services:
  node:
    container_name: node
    image: node:21.6.1-bookworm-slim
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
    tty: true