version: '3.9'
services:
  node-app:
    container_name: node-app
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
      - ./node/node_modules:/usr/src/app/node_modules
    environment:
      NODE_ENV: development
    networks:
      - app-network
    command: ["yarn", "dev"]
  
  mysql:
    container_name: mysql
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: node
      MYSQL_USER: node
      MYSQL_PASSWORD: node
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/ddl:/docker-entrypoint-initdb.d

    networks:
      - app-network

      
      
    
networks:
  app-network:
    driver: bridge

volumes:
  dbdata: